#pragma checksum "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4d907d0498b4aed4a5380690417f3ede211e3b14"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(WebApplication1.Pages.Pages_Index), @"mvc.1.0.razor-page", @"/Pages/Index.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.RazorPageAttribute(@"/Pages/Index.cshtml", typeof(WebApplication1.Pages.Pages_Index), null)]
namespace WebApplication1.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "E:\Azure POC\Solution1\WebApplication1\Pages\_ViewImports.cshtml"
using WebApplication1;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"4d907d0498b4aed4a5380690417f3ede211e3b14", @"/Pages/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"cd66e6c0b2d0593b97c0d67f6f506054866fe040", @"/Pages/_ViewImports.cshtml")]
    public class Pages_Index : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 3 "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml"
  
    ViewData["Title"] = "Home page 111";
    string pm = Model.wmessage;

#line default
#line hidden
            BeginContext(108, 39, true);
            WriteLiteral("\r\n<div>\r\n    <p>\r\n        Hellow World ");
            EndContext();
            BeginContext(148, 17, false);
#line 10 "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml"
                Write(ViewData["Title"]);

#line default
#line hidden
            EndContext();
            BeginContext(165, 41, true);
            WriteLiteral("\r\n\r\n    </p>\r\n    <p>\r\n        test test ");
            EndContext();
            BeginContext(207, 2, false);
#line 14 "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml"
             Write(pm);

#line default
#line hidden
            EndContext();
            BeginContext(209, 31, true);
            WriteLiteral("\r\n    </p>\r\n</div>\r\n\r\n\r\n<div>\r\n");
            EndContext();
#line 20 "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml"
     foreach (var product in Model.Products)
    {

#line default
#line hidden
            BeginContext(291, 5, true);
            WriteLiteral(" <p> ");
            EndContext();
            BeginContext(297, 15, false);
#line 21 "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml"
     Write(product.ModelId);

#line default
#line hidden
            EndContext();
            BeginContext(312, 10, true);
            WriteLiteral(" -------- ");
            EndContext();
            BeginContext(323, 17, false);
#line 21 "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml"
                               Write(product.ModelName);

#line default
#line hidden
            EndContext();
            BeginContext(340, 4, true);
            WriteLiteral("</p>");
            EndContext();
#line 21 "E:\Azure POC\Solution1\WebApplication1\Pages\Index.cshtml"
                                                          }

#line default
#line hidden
            BeginContext(347, 102, true);
            WriteLiteral("\r\n\r\n\r\n</div>\r\n<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\" data-interval=\"6000\">\r\n");
            EndContext();
            BeginContext(1084, 10, true);
            WriteLiteral("</div>\r\n\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IndexModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<IndexModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<IndexModel>)PageContext?.ViewData;
        public IndexModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591
